### PR TITLE
Check for rbenv in addition to rvm when installing soloist to avoid sudo

### PR DESCRIPTION
**Pull request by mikesplain**
First of all, great app! I'm a big fan. I ran into an issue running the script on an rbenv box and wanted to add in a line to check for rbenv just like the rvm line that was already in place.  Test suite passed before and after the change.  Thanks!

### CODE REVIEW

**Comment by tommyh** [comment]
Thanks for this pullrequest, sorry it's taken me a while to get back to you.

Right now there are no automated tests which actually run the shell script - only some highlevel tests which verify there is correct text in it.

I'm planning on setting up a Virtualbox image (with xcode + developer tools), so that I can quickly manually verify stuff like this.

I will try to merge this soon.

**Comment by mikesplain** [comment]
No worries at all!

You may want to give Vagrant http://www.vagrantup.com a try. It's
perfect for stuff like this. There's also a railscast if you're not
familiar (http://railscasts.com/episodes/292-virtual-machines-with-vagrant).
 If I get a second this weekend, maybe I'll give a stab at a vagrant script.

Good luck! Thanks for the great app!

**Comment by tommyh** [comment]
Hey,

I haven't had the time to test this - sorry.  Is @derekprior right that a `rbenv rehash` would be needed to make this work?

Tom

**Comment by mikesplain** [comment]
Yeah.. he's right. I haven't gotten a chance to dig back in and add that. I
was going to setup a proper vagrant setup for this... should have time this
week.

**Pull request closed without merging**
